default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: shortly_development

test:
  <<: *default
  database: shortly_test
  
production:
  primary: &primary_production
    <<: *default
    database: shortly_production
    username: shortly
    password: <%= ENV["SHORTLY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: shortly_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: shortly_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: shortly_production_cable
    migrations_paths: db/cable_migrate
